### ISSUE TITLE
Want to try OMOP on FHIR

### ISSUE THREAD

**Issue by kridsadakorn** [omoponfhir/omoponfhir-main-v54-r4#3]
Hi, I would like to try OMOP on FHIR
I tried to build a docker and it was successful.

I wonder once we start the docker container, what exact URL to use?

I tried in open the browser like localhost:8080, didn't work
Or after setting up the environment variables and trying something like localhost:8080/omoponfhir, didn't work.

It would be great if you could add a bit more detail in README on where to start after docker.

Thank you.

**Comment by myungchoi** [comment]
localhost:8080 is correct URL if you are running the Dockerized image at the same PC (running docker and browser in the same PC). If you are getting error, please see if Docker logs have any exceptions. (sudo docker logs <omoponfhir_container_id>)

Did you set up the OMOP DB and created necessary f_* tables and views?  This is for OMOP v5.4. You need to have a match version of OMOP as well. If this is not set up correctly, the OMOPonFHIR server will fail to launch.

**Comment by milanwillaert** [comment]
Hi, I'm having similar issues as well.
Right now I cannot get omop on fhir working by building the image.
When doing so it's having some kind of log4j import error.
I have tried both the main branch and the v1.7 branch

It would help a lot if there are prebuild images pushed to a public repository like dockerhub so that it's easy to compare.

Also, I believe there is a version conflict because the tomcat base image version is not very specific and hence can cause version conflicts when rebuilding later. Publishing working images would help others a lot.

I hope you can resolve this.
Kind regards



![Image](https://github.com/user-attachments/assets/97c9c5ca-7a66-4eb4-842a-ca6c37b72f4a)

**Comment by milanwillaert** [comment]
@myungchoi could you give us any further information on this?

**Comment by myungchoi** [comment]
Usually, the exception you have is in my case from the version you use for Java and tomcat. The dockerfile has the versions that I am using. Can you try with Java 21? I will upload my war file in the latest release section. Please see if you can run it from tomcat.

**Comment by milanwillaert** [comment]
I used the dockerfile build on the main branch for this, nothing else.

**Comment by milanwillaert** [comment]
I have build the dockerfile using the war file that you presented.

![Image](https://github.com/user-attachments/assets/5b9703ad-bc4f-40a5-a0e9-8c1a48fe9570)

Right now the server starts up properly, that said, it's not using the current hapi version of the main branch as you can see in the screenshot below.
It's using the 6.4.1 hapi version not the 7.6.1 version as I would expect from the normal build.
https://github.com/omoponfhir/omoponfhir-r4-server/blob/sqlRender/pom.xml 



![Image](https://github.com/user-attachments/assets/589d7321-4dbe-46b1-af67-596be39e739c)

**Comment by milanwillaert** [comment]
I have build the dockerfile using the war file that you presented.

![Image](https://github.com/user-attachments/assets/5b9703ad-bc4f-40a5-a0e9-8c1a48fe9570)

The server still doesn't start the omop on fhir application

![Image](https://github.com/user-attachments/assets/de40fb6c-fa47-4fb3-bf0e-ab8b7c8a3aff)

![Image](https://github.com/user-attachments/assets/478c4530-5c0a-46bf-81a7-9b0573fc080c)



![Image](https://github.com/user-attachments/assets/f17ceff6-9047-47cc-b820-50ea69e5b3fe)

![Image](https://github.com/user-attachments/assets/7be8ab9a-697d-4e44-9268-f59da24797e3)



I added the logs which show the JVM and Tomcat version, I believe the jre21 tomcat server / image you are using is a different one, possibly as you have a local cached version which doesn't match my image. jre21 is a wide tag as far as I can see.

performing a docker inspect on my image allows me to have some key details on the TOMCAT version used, also with a HASH:

![Image](https://github.com/user-attachments/assets/c80327f9-dd8c-442c-b03a-8e00b092e3c1)

**Comment by milanwillaert** [comment]
@myungchoi 
I hope this information helps.

**Comment by myungchoi** [comment]
That helps. I think it's missing the environment variables. The following environment variables need to be passed when building the docker image to run

The below is example environment variables if you use postgresql database.

export JDBC_URL="jdbc:postgresql://<your db host url>:5432/<your database name>"
export JDBC_USERNAME="<username>"
export JDBC_PASSWORD="<password>"
export JDBC_DRIVER="org.postgresql.Driver"
export JDBC_DATASOURCENAME="org.postgresql.ds.PGSimpleDataSource"
export JDBC_POOLSIZE=10
export JDBC_DATA_SCHEMA="<schema name for the OMOP database>"
export JDBC_VOCABS_SCHEMA="<if you have separate schema for the vocabulary related tables, put the name here.  if all in the same schema, this should be same as JDBC_DATA_SCHEMA"
export SMART_INTROSPECTURL="https://<your FHIR server URL or localhost:8080>/smart/introspect"
export SMART_AUTHSERVERURL="https://<your FHIR server URL or localhost:8080>/smart/authorize"
export SMART_TOKENSERVERURL="http://<your FHIR server URL or localhost:8080>/smart/token"
export AUTH_BEARER="<static token string. You can delete this line if you do not want set this static one>"
export AUTH_BASIC="<username and password in this format:  username:password"
export FHIR_READONLY="False"
export SERVERBASE_URL="<https://<your FHIR server URL or http://localhost:8080>/fhir/"
export LOCAL_CODEMAPPING_FILE_PATH="/tmp"
export MEDICATION_TYPE="code"
export TARGETDATABASE="postgresql"
export OMOPONFHIR_NAME="<your OMOPonFHIR server name. This can be anything>"

**Comment by milanwillaert** [comment]
Hi @myungchoi 
I have tried it and to no avail.

![Image](https://github.com/user-attachments/assets/90e635b2-27d0-4224-95d8-8898faf3d8f6)


My Dockerfile which simply builds using the war you provided
```
#Build the Tomcat container
FROM tomcat:jre21
#set environment variables below and uncomment the line. Or, you can manually set your environment on your server.
#ENV JDBC_URL=jdbc:postgresql://<host>:<port>/<database> JDBC_USERNAME=<username> JDBC_PASSWORD=<password>

# Copies updated server.xml to increase HTTP Header Length allowed
COPY server.xml $CATALINA_HOME/conf/

# Copy GT-FHIR war file to webapps.
#COPY --from=builder /usr/src/app/omoponfhir-r4-server/target/omoponfhir-r4-server.war $CATALINA_HOME/webapps/ROOT.war
COPY omoponfhir-r4-server.war $CATALINA_HOME/webapps/ROOT.war

EXPOSE 8080

```

My docker compose file, the postgres I already tested with a different application.
```
version: "3.9"

services:
  omoponfhir:
    build:
        context: .
        dockerfile: ./Dockerfile-1.7-war

    ports:
      - "8080:8080"
    environment:
      - JDBC_URL=jdbc:postgresql://:5432/
      - JDBC_DRIVER=org.postgresql.Driver
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=password
      - JDBC_POOLSIZE=10
      - JDBC_DATA_SCHEMA="omop54"
      - JDBC_DATASOURCENAME="org.postgresql.ds.PGSimpleDataSource"
      - SERVERBASE_URL=http://localhost:8080/fhir/
      - SMART_INTROSPECTURL=http://localhost:8080/smart/introspect
      - SMART_AUTHSERVERURL=http://localhost:8080/smart/authorize
      - SMART_TOKENSERVERURL=http://localhost:8080/smart/token
      - AUTH_BEARER=12345
      - AUTH_BASIC=client:secret
      - FHIR_READONLY=False
      - MEDICATION_TYPE=code
      - LOCAL_CODEMAPPING_FILE_PATH="/tmp"
      - TARGETDATABASE="postgresql"
      - OMOPONFHIR_NAME=""
    depends_on:
      omop54:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure

  omop54:
    # local image for now
    image: omop-54-postgresql_omop54
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - CONSTRAINTS=false
      - OMOP_ON_FHIR=true
    volumes:
      - /home/milan/Git/codeflow/ATHENA:/VOCAB
    healthcheck:
      test: ["CMD", "./omoponfhir/healthcheck.sh"]
      interval: 15s
      timeout: 10s
      retries: 10000
```


Could you please push an image to the release https://docs.docker.com/reference/cli/docker/image/save/ or to dockerhub, comparing like this is very hard.
I am trying to resolve the dependency conflict issue myself and it's not very easy as an outsider who has little knowledge about the java / tomcat ecosystem.


Thanks in advance
